CountHeaders: CountHeaders.o LinkedList.o HashTable.o Assert333.o
	gcc -Wall -std=gnu99 -o CountHeaders CountHeaders.o LinkedList.o HashTable.o Assert333.o

CountHeaders.o: CountHeaders.c
	gcc -Wall -std=gnu99 -o CountHeaders.o -c CountHeaders.c

LinkedList.o: LinkedList.c 
	gcc -Wall -std=gnu99 -o LinkedList.o -c LinkedList.c 

HashTable.o: HashTable.c
	gcc -Wall -std=gnu99 -o HashTable.o -c HashTable.c

Assert333.o: Assert333.c
	gcc -Wall -std=gnu99 -o Assert333.o -c Assert333.c
